from __future__ import annotations

from fastapi import APIRouter

from app.api.v1 import (
    agents,
    alerts,
    audit,
    auth,
    chat,
    evaluation,
    guardrails,
    knowledge,
    marketplace,
    memory,
    model_management,
    model_routing,
    multi_agent,
    observability,
    orgs,
    permissions,
    prompt_studio,
    published,
    roles,
    runtime,
    scheduler,
    security,
    system,
    tenants,
    tools_center,
    users,
    workflows,
)

api_router = APIRouter()

for module in [
    auth,
    tenants,
    users,
    orgs,
    roles,
    permissions,
    agents,
    workflows,
    model_management,
    model_routing,
    tools_center,
    knowledge,
    memory,
    observability,
    audit,
    security,
    evaluation,
    alerts,
    runtime,
    system,
    chat,
    multi_agent,
    guardrails,
    prompt_studio,
    published,
    marketplace,
    scheduler,
]:
    api_router.include_router(module.router)
